"""
Search Queries for Image Classification Dataset

Defines search queries for each category in the classifier.
"""

SEARCH_QUERIES = {
    'bird': [
        'bird flying',
        'crow',
        'eagle',
        'parrot',
        'pidgeon',
        'seagull',
        'hawk',
        'owl',
        'hummingbird',
        'sparrow',
        'robin',
        'cardinal bird',
        'blue jay',
        'woodpecker',
        'pelican',
        'flamingo',
        'toucan',
        'peacock',
        'swan',
        'duck',
    ],
    'plane': [
        'airplane flying',
        'airplane',
        'jet plane',
        'prop plane',
        'plane landing',
        'commercial airplane',
        'passenger jet',
        'boeing aircraft',
        'airbus plane',
        'fighter jet',
        'military aircraft',
        'biplane',
        'cessna aircraft',
        'private jet',
        'cargo plane',
        'airplane takeoff',
        'plane in sky',
        'aircraft cockpit',
    ],
    'superman': [
        'superman flying',
        'superman',
        'superman costume',
        'superman comic',
        'superman live-action',
        'superman movie',
        'superman cape',
        'clark kent superman',
        'superman logo',
        'superman action figure',
        'superman cosplay',
        'man of steel',
        'superman cartoon',
        'superman animated',
        'superman artwork',
    ],
    'other': [
        'person',
        'crowd',
        'portrait',
        'face',
        'city',
        'street',
        'building',
        'skyscraper',
        'bridge',
        'interior',
        'room',
        'kitchen',
        'office',
        'furniture',
        'spaceship',
        'car',
        'truck',
        'train',
        'helicopter',
        'boat',
        'motorcycle',
        'bicycle',
        'construction',
        'pattern',
        'bulldozer',
        'tractor',
        'landscape',
        'mountain',
        'forest',
        'desert',
        'beach',
        'ocean',
        'waterfall',
        'flowers',
        'trees',
        'snow',
        'rocks',
        'underwater',
        'fish',
        'insects',
        'reptile',
        'dog',
        'cat',
        'food',
        'restaurant',
        'painting',
        'illustration',
        'anime',
        'cartoon',
        'screenshot',
        'texture',
        'smartphone',
        'laptop',
        'computer',
        'technology',
        'gadget',
        'camera',
        'watch',
        'clock',
        'book',
        'library',
        'classroom',
        'hospital',
        'park',
        'garden',
        'playground',
        'stadium',
        'church',
        'temple',
        'castle',
        'monument',
        'statue',
        'fountain',
        'rainbow',
        'sunset',
        'sunrise',
        'clouds',
        'lightning',
        'moon',
        'stars',
        'galaxy',
        'planet',
        'abstract art',
        'graffiti',
        'mural',
        'sculpture',
        'pottery',
        'jewelry',
        'clothing',
        'shoes',
        'hat',
        'backpack',
        'sunglasses',
        'umbrella',
        'balloon',
        'kite',
        'flag',
        'sign',
        'billboard',
        'traffic light',
        'fire hydrant',
        'bench',
        'lamp',
        'door',
        'window',
        'stairs',
        'elevator',
        'escalator',
    ]
}


def load_search_queries():
    """Return the search queries dictionary."""
    return SEARCH_QUERIES